	#base	"../../_custom/resource/ui/huditemeffectmeter_halloweensouls.res"
	#base	"../../#users/dane/resource/ui/huditemeffectmeter_halloweensouls.res"
	#base	"../../_eleven/resource/ui/huditemeffectmeter_halloweensouls.res"
	#base	"../../_jofrehud/resource/ui/huditemeffectmeter_halloweensouls.res"
	#base	"../../_tf2hud/resource/ui/huditemeffectmeter_halloweensouls.res"