	#base	"../../#users/custom/resource/ui/hudplayerhealth.res"
	#base	"../../_jofrenew/_customization/resource/ui/hudplayerhealth - style.res"	
	#base	"../../_jofrenew/resource/ui/hudplayerhealth.res"
	#base	"../../_jofrenew/_customization/resource/ui/healthcross.res"		
	#base	"../../_jofrehud/resource/ui/hudplayerhealth.res"	
	#base	"../../_tf2hud/resource/ui/hudplayerhealth.res"