	#base	"../../custom/resource/ui/surveypanel_matchquality.res"
	#base	"../../_eleven/resource/ui/surveypanel_matchquality.res"
	#base	"../../_opd/resource/ui/surveypanel_matchquality.res"
	#base	"../../_opd/_tf2fix/resource/ui/surveypanel_matchquality.res"
//	#base	"../../_tf2hud/resource/ui/surveypanel_matchquality.res"