	#base "../custom/resource/clientscheme.res"
	#base "../_eleven/resource/clientscheme.res"
	#base "../_opd/resource/clientscheme.res"
	#base "../_opd/_tf2exp/clientscheme.res"	
	//#base "../_tf2hud/resource/clientscheme.res"